name: test Project
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v4
      - name: install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: install dependencies
        run: npm install
      - name: run tests
        run: npm test